In [1]:
import torch
import GNet

In [2]:
m = GNet.GNet_MLP()

In [21]:
m = GNet.ModelLoader(GNet.ModelType.last_epoch)

Loaded model weights from last_epoch_net.pth.


In [22]:
m.generate(torch.rand((10,988)))

tensor([[0.3321, 0.6679],
        [0.3459, 0.6541],
        [0.3431, 0.6569],
        [0.3364, 0.6636],
        [0.3386, 0.6614],
        [0.3376, 0.6624],
        [0.3401, 0.6599],
        [0.3463, 0.6537],
        [0.3445, 0.6555],
        [0.3405, 0.6595]])

In [5]:
import librosa

In [6]:
a, b = librosa.load('D1738416T14198969(Web)_[cut_111sec].mp3')
a = librosa.resample(a, orig_sr=b, target_sr=16000)

In [7]:
t = a[:16000 * 5]

In [8]:
process = GNet.WaveFormProcess()

In [9]:
n = process.split_audio(a)

In [10]:
import numpy as np

In [11]:
cc = np.array(n)

In [12]:
cc.shape

(23, 80000)

In [17]:
torch.tensor(process.feature(cc))

tensor([[2.7770e-01, 0.0000e+00, 2.7770e-01,  ..., 0.0000e+00, 3.0600e-02,
         1.8068e-02],
        [5.5560e-02, 3.5454e-04, 5.5560e-02,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [9.4432e-02, 1.1609e-03, 9.4432e-02,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        ...,
        [5.7025e-02, 2.1463e+00, 5.6976e-02,  ..., 0.0000e+00, 4.6203e-03,
         2.7281e-03],
        [6.8357e-02, 5.3117e-03, 6.8357e-02,  ..., 6.5788e-02, 2.1928e-01,
         1.6516e-01],
        [1.4118e-01, 0.0000e+00, 1.4118e-01,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00]])

In [18]:
process.pipe(a)

tensor([[2.7770e-01, 0.0000e+00, 2.7770e-01,  ..., 0.0000e+00, 3.0600e-02,
         1.8068e-02],
        [5.5560e-02, 3.5454e-04, 5.5560e-02,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [9.4432e-02, 1.1609e-03, 9.4432e-02,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        ...,
        [5.7025e-02, 2.1463e+00, 5.6976e-02,  ..., 0.0000e+00, 4.6203e-03,
         2.7281e-03],
        [6.8357e-02, 5.3117e-03, 6.8357e-02,  ..., 6.5788e-02, 2.1928e-01,
         1.6516e-01],
        [1.4118e-01, 0.0000e+00, 1.4118e-01,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00]])

In [25]:
m.generate(process.pipe(a)).argmax(-1)

tensor(1.)